import type { Session } from "./model";

export const fixtureSessions: readonly Session[] = [
  {
    id: "api-sentinel",
    name: "API Sentinel",
    agent: "Codex",
    state: "waiting_approval",
    connection: "connected",
    objective: "Harden refresh-token rotation without changing the public API.",
    repository: "alt-ctrl",
    worktree: "worktrees/api-sentinel",
    branch: "agent/refresh-rotation",
    elapsed: "18m 42s",
    currentTool: "cargo test -p auth-core",
    contextPercent: 63,
    changedFiles: 4,
    gitState: "4 modified",
    testSummary: "42 passed · 1 pending",
    testTone: "warning",
    permission: "Edit",
    attentionCount: 1,
    output: [
      { tone: "muted", text: "turn.started · analysing refresh boundary" },
      {
        tone: "plain",
        text: "I found one stale-token race in rotate_refresh_token().",
      },
      { tone: "accent", text: "✓ added a single-use token guard" },
      {
        tone: "plain",
        text: "Running targeted tests before changing the public handler…",
      },
      { tone: "warning", text: "approval required · cargo test -p auth-core" },
    ],
    plan: [
      { label: "Reproduce the stale-token race", state: "done" },
      { label: "Add single-use rotation guard", state: "done" },
      { label: "Run focused auth tests", state: "active" },
      { label: "Review public API diff", state: "queued" },
    ],
    approval: {
      id: "approval-17",
      action: "Run local test command",
      command: "cargo test -p auth-core refresh_rotation -- --nocapture",
      risk: "Medium",
      rule: "Edit profile · allow-listed local test",
      sideEffect: "Starts a local test process in the assigned worktree.",
    },
  },
  {
    id: "ui-forge",
    name: "UI Forge",
    agent: "Claude Code",
    state: "running",
    connection: "connected",
    objective:
      "Build the controller-first Mission Control layout and focus system.",
    repository: "alt-ctrl",
    worktree: "worktrees/ui-forge",
    branch: "agent/mission-control",
    elapsed: "11m 09s",
    currentTool: "Editing app/src/style.css",
    contextPercent: 41,
    changedFiles: 7,
    gitState: "7 modified",
    testSummary: "Typecheck clean",
    testTone: "success",
    permission: "Edit",
    attentionCount: 0,
    output: [
      { tone: "muted", text: "turn.started · mapping 1920×1080 layout" },
      {
        tone: "plain",
        text: "Building the session card grid and attention rail.",
      },
      { tone: "accent", text: "✓ deterministic focus order wired" },
      {
        tone: "plain",
        text: "Now tuning large-format typography and contrast.",
      },
    ],
    plan: [
      { label: "Establish visual tokens", state: "done" },
      { label: "Build Mission Control grid", state: "active" },
      { label: "Add controller legend", state: "queued" },
      { label: "Validate keyboard parity", state: "queued" },
    ],
  },
  {
    id: "test-pilot",
    name: "Test Pilot",
    agent: "Codex",
    state: "failed",
    connection: "connected",
    objective: "Add crash-recovery fixtures for the durable event store.",
    repository: "alt-ctrl",
    worktree: "worktrees/test-pilot",
    branch: "agent/recovery-fixtures",
    elapsed: "26m 31s",
    currentTool: "cargo test -p event-store",
    contextPercent: 78,
    changedFiles: 3,
    gitState: "3 modified",
    testSummary: "18 passed · 2 failed",
    testTone: "danger",
    permission: "Build",
    attentionCount: 2,
    output: [
      { tone: "muted", text: "test.run · event-store recovery suite" },
      { tone: "accent", text: "✓ 18 assertions passed" },
      { tone: "danger", text: "✕ reopen_after_truncated_wal" },
      { tone: "danger", text: "✕ checkpoint_never_leads_event" },
      {
        tone: "plain",
        text: "The fixture needs a deterministic crash boundary.",
      },
    ],
    plan: [
      { label: "Build restart fixture", state: "done" },
      { label: "Inject WAL interruption", state: "active" },
      { label: "Prove checkpoint ordering", state: "queued" },
    ],
  },
  {
    id: "docs-lens",
    name: "Docs Lens",
    agent: "Generic PTY",
    state: "completed",
    connection: "disconnected",
    objective:
      "Review controller ecosystem references and record adoption decisions.",
    repository: "alt-ctrl",
    worktree: "worktrees/docs-lens",
    branch: "agent/reference-review",
    elapsed: "08m 14s",
    currentTool: "Session complete",
    contextPercent: 22,
    changedFiles: 1,
    gitState: "clean",
    testSummary: "Review complete",
    testTone: "success",
    permission: "Observe",
    attentionCount: 0,
    output: [
      { tone: "muted", text: "session.completed · reference review" },
      {
        tone: "accent",
        text: "✓ 9 projects classified by license and relevance",
      },
      {
        tone: "plain",
        text: "Adoption decisions written to docs/reference-research.md.",
      },
    ],
    plan: [
      { label: "Review controller projects", state: "done" },
      { label: "Review orchestrators", state: "done" },
      { label: "Record license boundaries", state: "done" },
    ],
  },
] as const;
